#!/usr/bin/env bash

case $1 in
    level)
        jq '. | with_entries(select(.key | test(".*level.*")))' data/character.json
        ;;
    inv)
        jq '.inventory[] as $inv | $inv | select($inv.quantity > 0)' data/character.json
        ;;
    *)
        jq '{name, account, level, xp, gold, hp, x, y}' data/character.json
esac

