#!/usr/bin/env bash

. validate_args name -- $@

response=$(artifacts gatheringMyNameActionGatheringPost \
    name=$name)

. check_error $response

echo $response | jq .data.cooldown > data/cooldown.json
echo $response | jq .data.character > data/character.json
echo $response | jq .data.details > data/gather.json

echo $response | jq '.data.details'
