#!/usr/bin/env bash

. validate_args name x y -- $@

response=$(artifacts moveMyNameActionMovePost \
    name=$name x==$x y==$y)

. check_error $response

echo $response | jq .data.destination > data/destination.json
echo $response | jq .data.character > data/character.json
echo $response | jq .data.cooldown > data/cooldown.json

echo $response | jq '.data.character as $char | {
    name: $char.name,
    cooldown: ($char.cooldown_expiration[:19] | strptime("%Y-%m-%dT%H:%M:%S") | mktime)
}'
