#!/usr/bin/env bash

. validate_args name x y -- $@

response=$(artifacts moveMyNameActionMovePost \
    name=$name x==$x y==$y)

# get the datetime in unix epoch

echo $response

# -r is "raw output" which wont quote strings
iso_expire=$(echo $response | jq -r .data.cooldown.expiration)
epoch_expire=$(date -d $iso_expire --utc +%s)

echo $response | jq -r .data.cooldown.expiration

# do I want to build parsers for the different schemas?
# or at least save them in different locations?
# why not cache the character details in the data dir
